language: java
sudo: false
jdk: openjdk8
install: true
script: "./gradle/buildViaTravis.sh"
cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
after_success:
- "./gradlew jacocoTestReport coveralls"
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/40d8f3228ea299105c63
    on_success: always
    on_failure: always
    on_start: false
env:
  global:
  - secure: Co9eeWpxJjtc5w6Aa5Fzc+sJWO9RgLvXBAe0PItOG6CGINLBVG7/odornrnMUalFf+mIPrxKv+sCBvdLd962LgtK8Xp7d0T8WMJjvPkVn3YTkgHO1q3bRrt4H4URr0dUVGDqgyPf3gy4g7IsZFNxwtTVhIB4ZUhTaTmzfcnIGvA=
  - secure: KPQlSISIRisIP+LaVgFzYWWknBZZyeTJwNGA4Z3BR2s3Y9TfG9vabMkjTwve8ili8FtxiW3GZ0Nsas9xmqOXbdMe2gLnB7J5zp2xjOtqmQfOs482MZZC1+EP7tNSrX5wRNDND/AVTY9kRqbykWlmUGL4L73OJMewY+EXQzc2034=
  - secure: U7hbGwTSrrwm4FMBnsYV/eEGv7L+M2puZhyV7kV9XlguhNEoVCPU5tCY1QFlAehS7fkxjGpfyxX4RLkfdHMnTC1LfSDeiMS8GZgOsJrfrKtwyHXqgizxChAm9gVwwn/mFzT77UYfprLSiAowP5UeeB19tGusRmkUO1mgNsm+xwo=
  - secure: SAAiXc2zxcMbyR61Yzeqa8NLCg6KqpZs37DiTb2+hMNGLjv8dq2MyxTNVFk6VE2gYRlYIbbRcqrZjTwaqmpbzwZDuFfG7sByVPKcMSjzyQ1DSwQPKGKBGLqIXKay49MP9K+4/GNetQE/1gNq8pLrsaIrqhFEkDG3PmNdMrqQqc8=
  - secure: IqAkreTXLTCTUQMsyDxaRDs+3lT+OMQtHMx4a0aQ0lybFZOXjS2z18V7d9e/wcxjI165vL4IPGK76IpJRCtWPydcs7tBK5d2Ex/CRneoy1p57JXY0vcyKXT8XhXDUsSuSoh2QrhP762WE6+ABcNrhfyR8++rtob/iZzWyGLGtKs=
  - secure: IR1n/ZjpwgK+9SzNujyEW3Q15hPrK2v3rbhnrNLV/nfXInLUK1iu+7nt03zyaOXyfomsFegG4xZtZ/pDPwxT60i6lERkW/UyewddBoBjOuRzIZRKzXj1zbr6rrHHmUdr3jxtxloWjTjy5BGYJ68y4KS6NfUpH1Gj0cLjJaWAVQk=
